environment=local
browser=chrome
windowMaximize=true
driverPath=C:\\Users\\praga\\Downloads\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe
implicitlyWait=20
url=http://www.shop.demoqa.com
testDataResourcePath=src/test/resources/testDataResources/